name: Android CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get JRE 8
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: buildjre8.yml
          path: app_pojavlauncher/src/main/assets/components/jre-8
          workflow_conclusion: success
          repo: Vera-Firefly/android-openjdk-autobuild
          branch: main
          name: jre8-pojav

      - name: Get JRE21
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: buildjre21.yml
          path: app_pojavlauncher/src/main/assets/components/jre-21
          workflow_conclusion: success
          repo: Vera-Firefly/android-openjdk-autobuild
          branch: main
          name: jre21-pojav

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: main.yml
          path: app_pojavlauncher/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: official
          name: lwjgl

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.6.1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Debug
        run: |
          gradle :app_pojavlauncher:assembleDebug

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app_pojavlauncher/build/outputs/apk/debug/*

  buildnoruntime:
    runs-on: ubuntu-22.04
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: main.yml
          path: app_pojavlauncher/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: official
          name: lwjgl

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.6.1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Debug-noruntime
        run: |
          gradle :app_pojavlauncher:assembleDebug

      - name: Upload Debug-noruntime
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-noruntime
          path: app_pojavlauncher/build/outputs/apk/debug/*
